-- =============================================================================
-- JavierFitness Phase 1: Initial Schema
-- =============================================================================
-- Creates the complete database schema for authentication, role-based access,
-- and exercise library management. Includes RLS policies, Custom Access Token
-- Hook for JWT role injection, and auto-creation triggers.
--
-- Run this migration via Supabase SQL Editor or `supabase db push`.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. User role enum
-- -----------------------------------------------------------------------------
create type public.user_role as enum ('trainer', 'client');

-- -----------------------------------------------------------------------------
-- 2. Profiles table (extends auth.users)
-- -----------------------------------------------------------------------------
-- Stores user profile data linked to Supabase Auth. Each auth.users row gets
-- a corresponding profiles row via the handle_new_user trigger.
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  full_name text,
  role user_role not null default 'client',
  is_active boolean not null default false,    -- trainer must activate clients
  preferred_language text not null default 'es',
  theme text not null default 'dark',           -- dark/light theme preference
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.profiles is 'User profiles extending auth.users with role, activation status, and preferences';
comment on column public.profiles.is_active is 'Trainer must activate client accounts before they can access training features';
comment on column public.profiles.theme is 'User preferred UI theme: dark or light';

-- -----------------------------------------------------------------------------
-- 3. User roles table (for Custom Access Token Hook)
-- -----------------------------------------------------------------------------
-- Stores user roles separately from profiles so the Custom Access Token Hook
-- can inject the role into JWTs. This table is only readable by supabase_auth_admin.
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  role user_role not null,
  unique (user_id, role)
);

comment on table public.user_roles is 'User roles for Custom Access Token Hook JWT injection';

-- -----------------------------------------------------------------------------
-- 4. Exercises table
-- -----------------------------------------------------------------------------
-- Trainer-managed exercise library. Each exercise has a name and YouTube video link.
create table public.exercises (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  youtube_url text not null,
  created_by uuid references auth.users not null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.exercises is 'Exercise library managed by trainer, referenced in training plans';

-- -----------------------------------------------------------------------------
-- 5. Indexes for RLS performance
-- -----------------------------------------------------------------------------
-- Indexes on columns referenced in RLS policy conditions to prevent full table scans.
create index idx_profiles_role on public.profiles(role);
create index idx_profiles_is_active on public.profiles(is_active);
create index idx_user_roles_user_id on public.user_roles(user_id);
create index idx_exercises_created_by on public.exercises(created_by);

-- -----------------------------------------------------------------------------
-- 6. Enable Row Level Security on ALL tables
-- -----------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.exercises enable row level security;

-- -----------------------------------------------------------------------------
-- 7. RLS Policies for profiles
-- -----------------------------------------------------------------------------

-- Users can read their own profile
create policy "Users can view own profile"
on public.profiles for select
to authenticated
using (id = (select auth.uid()));

-- Trainer can view all profiles (for client management)
create policy "Trainer can view all profiles"
on public.profiles for select
to authenticated
using (
  (select auth.jwt()->>'user_role') = 'trainer'
);

-- Trainer can update any profile (for activation, role changes)
create policy "Trainer can update profiles"
on public.profiles for update
to authenticated
using (
  (select auth.jwt()->>'user_role') = 'trainer'
)
with check (
  (select auth.jwt()->>'user_role') = 'trainer'
);

-- Users can update their own profile (name, language, theme)
create policy "Users can update own profile"
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

-- -----------------------------------------------------------------------------
-- 8. RLS Policies for user_roles
-- -----------------------------------------------------------------------------
-- Only supabase_auth_admin can read user_roles (for the Custom Access Token Hook).
-- No other role should access this table directly.

create policy "Allow auth admin to read user roles"
on public.user_roles as permissive for select
to supabase_auth_admin
using (true);

-- -----------------------------------------------------------------------------
-- 9. RLS Policies for exercises
-- -----------------------------------------------------------------------------

-- Trainer can view all exercises
create policy "Trainer can view all exercises"
on public.exercises for select
to authenticated
using (
  (select auth.jwt()->>'user_role') = 'trainer'
);

-- Trainer can create exercises
create policy "Trainer can create exercises"
on public.exercises for insert
to authenticated
with check (
  (select auth.jwt()->>'user_role') = 'trainer'
);

-- Trainer can update exercises
create policy "Trainer can update exercises"
on public.exercises for update
to authenticated
using (
  (select auth.jwt()->>'user_role') = 'trainer'
)
with check (
  (select auth.jwt()->>'user_role') = 'trainer'
);

-- Trainer can delete exercises
create policy "Trainer can delete exercises"
on public.exercises for delete
to authenticated
using (
  (select auth.jwt()->>'user_role') = 'trainer'
);

-- Active clients can view exercises (needed for Phase 2 workout view)
create policy "Active clients can view exercises"
on public.exercises for select
to authenticated
using (
  (select auth.jwt()->>'user_role') = 'client'
  and exists (
    select 1 from public.profiles
    where profiles.id = (select auth.uid())
    and profiles.is_active = true
  )
);

-- -----------------------------------------------------------------------------
-- 10. Custom Access Token Hook function
-- -----------------------------------------------------------------------------
-- Injects the user_role claim into JWTs. Must be enabled in:
-- Supabase Dashboard -> Authentication -> Hooks -> Custom Access Token Hook
-- -> select public.custom_access_token_hook

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
as $$
declare
  claims jsonb;
  user_role_value public.user_role;
begin
  -- Fetch the user's role from user_roles table
  select role into user_role_value
  from public.user_roles
  where user_id = (event->>'user_id')::uuid;

  claims := event->'claims';

  if user_role_value is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role_value));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;

  event := jsonb_set(event, '{claims}', claims);
  return event;
end;
$$;

-- Grant permissions for the hook to work
grant usage on schema public to supabase_auth_admin;
grant execute on function public.custom_access_token_hook to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook from authenticated, anon, public;
grant all on table public.user_roles to supabase_auth_admin;
revoke all on table public.user_roles from authenticated, anon, public;

-- -----------------------------------------------------------------------------
-- 11. Profile auto-creation trigger (handle_new_user)
-- -----------------------------------------------------------------------------
-- Automatically creates a profile and user_roles entry when a new user signs up.
-- Reads full_name and role from raw_user_meta_data (passed during signUp).
-- Trainer is auto-activated; clients default to inactive.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role, is_active)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce((new.raw_user_meta_data->>'role')::public.user_role, 'client'),
    -- Trainer is auto-activated; clients require trainer activation
    case when coalesce((new.raw_user_meta_data->>'role')::public.user_role, 'client') = 'trainer'
      then true
      else false
    end
  );

  -- Also insert into user_roles for the Custom Access Token Hook
  insert into public.user_roles (user_id, role)
  values (
    new.id,
    coalesce((new.raw_user_meta_data->>'role')::public.user_role, 'client')
  );

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- -----------------------------------------------------------------------------
-- 12. Updated_at trigger
-- -----------------------------------------------------------------------------
-- Reusable function that automatically sets updated_at = now() on UPDATE.

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Attach to profiles table
create trigger profiles_updated_at
  before update on public.profiles
  for each row execute function public.update_updated_at_column();

-- Attach to exercises table
create trigger exercises_updated_at
  before update on public.exercises
  for each row execute function public.update_updated_at_column();
